name: Download new specs if available
on:
  schedule:
    - cron: "49 1 * * *" # 01:49 every day.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: "1.46.3"
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Sync specs
      run: ./sync.ts
    - name: Push new specs
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        ./commit.ts
